### ISSUE TITLE
Wichtige nicht seriöse frage

### ISSUE THREAD

**Issue by DasDarki** [ZargorNET/DiscordBot#1]
Ihhhhh warum Rust?! Obwohl, du warst ja schon damals (als du noch bei Bellaza warst) so Rust-fixiert :D 

P.S. ja ich stalke dich :P

**Comment by ZargorNET** [comment]
Weil's geil ist :D Manchmal echt nerven raubend und ich bin noch lange kein Profi in der Sprache, aber sie funktioniert einfach so gut - falls sie einmal compiled^^. Und dazu ist's geil, wenn man halt einfach dann Programme hat, die nur 10 MB an Arbeitsspeicher reservieren und trzdm verdammt schnell sind :D Dazu kommt halt noch, dass ich finde, dass Rust mega die logische Sprache ist, wenn man sich einmal mit beschäftigt hat. Außerdem ist es ja eig. eine System-Language, aber das Library-Management ist um Weeeelten leichter als in bspw. C++ mit CMake^^

> P.S. ja ich stalke dich :P

Yeah, bin genauso :P xD

**Comment by ZargorNET** [comment]
Achso und noch ganz wichtig: Ja, ich kann damit auch TS Plugins schreiben; schon ausprobiert ;)

**Comment by DasDarki** [comment]
Genau dafür arbeite ich gerade nochmals an einer Lösung: Hatte ja mal versucht mit C# einen Wrapper für das TS3 SDK zu schreiben, nun mache ich das mit Java. Falls du mal in meine Repos guckst, da ist Pegasus und das funktioniert sogar schon.... Hat aber noch keine Funktion. Ich kann lediglich JAR files in einem C TS3 Plugin laden :D
